version: '3.9'

networks:
  default:
      name: "seaf"

services:
  db:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: seaf-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $DB_MARIADB_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_LOG_CONSOLE=true
      - TIME_ZONE=$TIME_ZONE
    volumes:
      - $DATADIR/mysql:/var/lib/mysql:Z

  memcached:
    image: memcached:$DB_MEMCACHED_VERSION
    container_name: seaf-memcached
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    entrypoint: memcached -m 256
    environment:
      - TIME_ZONE=$TIME_ZONE

      
  seafile:
    image: $SEAFILE_REPO:$SEAFILE_VERSION
    container_name: seaf
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "$SEAFILE_HTTP_PORT:80"
      - "$SEAFILE_HTTPS_PORT:443"  # Only if using HTTPS
    volumes:
      - $CONFIGDIR/nginx:/shared/nginx:Z              # nginx configuration files
      - $DATADIR/seafile_data:/shared/seafile/:Z       # data for seafile and seahub
      - $DATADIR/seafile_logs:/shared/logs/:Z         # Seafile logs directory
      - ./scripts:/opt/scripts:Z                       # custom scripts for post-deployment
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=$DB_MARIADB_PASSWORD
      - TIME_ZONE=$TIME_ZONE
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD  
      - SEAFILE_SERVER_HOSTNAME=$SEAFILE_SERVER_HOSTNAME  
      - SEAFILE_SERVER_LETSENCRYPT=false
    depends_on:
      - db
      - memcached

### Optional Office Preview
  # office-preview:
  #   image: seafileltd/office-preview:latest
  #   container_name: seafile-office-preview
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   depends_on:
  #     - seafile
  #   ports:
  #     - "8089:8089"
  #   command: bash start.sh
  #   volumes:
  #     - $DATADIR/office-preview/shared:/shared 

