version: '3.7'

volumes:
  elasticsearch_data:
networks:
  default:
      name: "$SEAFILE_NAME"

services:
  db:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $SEAFILE_NAME-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $DB_MARIADB_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_LOG_CONSOLE=true
      - TIME_ZONE=$TIME_ZONE
    volumes:
      - $DATADIR/mysql:/var/lib/mysql

  memcached:
    image: memcached:$DB_MEMCACHED_VERSION
    container_name: $SEAFILE_NAME-memcached
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    entrypoint: memcached -m 256
    environment:
      - TIME_ZONE=$TIME_ZONE


  elasticsearch:
    image: elasticsearch:$DB_ELASTICSEARCH_VERSION
    container_name: $SEAFILE_NAME-elasticsearch
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - TIME_ZONE=$TIME_ZONE
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      # Elasticsearch data persistent store. 
      # Don't use local mount, it will mess up permissions (elasticsearch uses elasticsearch user with 1000:1000 UID:GID)
      - elasticsearch_data:/usr/share/elasticsearch/data  

      
  seafile:
    image: $SEAFILE_REPO:$SEAFILE_VERSION
    container_name: $SEAFILE_NAME
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "$SEAFILE_HTTP_PORT:80"
      - "$SEAFILE_HTTPS_PORT:443"  # Only if using HTTPS
    volumes:
      - $CONFIGDIR/nginx:/shared/nginx:ro   # nginx configuration files
      - $DATADIR/seafile_data:/shared/seafile/ # data for seafile and seahub
      - ./scripts:/opt/scripts
      - $DATADIR/seafile_logs:/shared/logs   # Seafile log directory

    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=$DB_MARIADB_PASSWORD
      - TIME_ZONE=$TIME_ZONE
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_USER
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_PASSWORD    
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=$SEAFILE_HOST_URL
    depends_on:
      - db
      - memcached
      - elasticsearch


### Optional Office Preview
  # office-preview:
  #   image: seafileltd/office-preview:latest
  #   container_name: seafile-office-preview
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   depends_on:
  #     - seafile
  #   ports:
  #     - "8089:8089"
  #   command: bash start.sh
  #   volumes:
  #     - $DATADIR/office-preview/shared:/shared 

