version: '3.7'

networks:
  default:
      name: "$SEAFILE_NAME"

volumes:
  seafile_data:
  elasticsearch_data:
  mysql_data:

services:
  db:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $SEAFILE_NAME-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $DB_MARIADB_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - mysql_data:/var/lib/mysql

  memcached:
    image: memcached:$DB_MEMCACHED_VERSION
    container_name: $SEAFILE_NAME-memcached
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    entrypoint: memcached -m 256

  elasticsearch:
    image: elasticsearch:$DB_ELASTICSEARCH_VERSION
    container_name: $SEAFILE_NAME-elasticsearch
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.

      
  seafile:
    image: $SEAFILE_REPO:$SEAFILE_VERSION
    container_name: $SEAFILE_NAME
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "$SEAFILE_HTTP_PORT:80"
      # - "$SEAFILE_HTTPS_PORT:443"  # Only uncomment if using HTTPS
    volumes:
      - seafile_data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=$DB_MARIADB_PASSWORD
      - TIME_ZONE=$TIME_ZONE
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_USER
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_PASSWORD    
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=$SEAFILE_HOST_URL
    depends_on:
      - db
      - memcached
      - elasticsearch
